sudo: required
language: csharp
os: linux
dist: trusty
mono: none
dotnet: 1.0.4
branches:
  only:
    - master
before_script:
  - chmod a+x ./scripts/build.sh
  - chmod a+x ./scripts/test.sh
script:
  - ./scripts/build.sh
  - ./scripts/test.sh
after_success:
  - docker login -u $DOCKER_UNAME -p $DOCKER_PASS
  - export REPO=selcukusta/netcore-travis-ci-test-sample
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker tag $REPO:$TAG $REPO:netcoresample-build-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
